# Generated by Django 5.0.2 on 2024-02-12 05:44

import django_prometheus.models
import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('resolution', models.CharField(max_length=10)),
                ('lastModified', models.DateTimeField()),
                ('content', jsonfield.fields.JSONField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('charts'), models.Model),
        ),
        migrations.CreateModel(
            name='DrawingTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('tool', models.CharField(max_length=200)),
                ('content', jsonfield.fields.JSONField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('drawing_template'), models.Model),
        ),
        migrations.CreateModel(
            name='StudyTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ownerSource', models.CharField(db_index=True, max_length=200)),
                ('ownerId', models.CharField(db_index=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('content', jsonfield.fields.JSONField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('study_template'), models.Model),
        ),
    ]
